chore(deps-rs): bump the patch group with 3 updates (#1854)
Bumps the patch group with 3 updates:
[cc](https://github.com/rust-lang/cc-rs),
[bytemuck](https://github.com/Lokathor/bytemuck) and
[clap](https://github.com/clap-rs/clap).

Updates `cc` from 1.2.66 to 1.2.67
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/rust-lang/cc-rs/releases">cc's
releases</a>.</em></p>
<blockquote>
<h2>cc-v1.2.67</h2>
<h3>Other</h3>
<ul>
<li>Fix clippy warning (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1788">#1788</a>)</li>
<li>Regenerate target info (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1785">#1785</a>)</li>
<li>Add support for <code>aarch64-unknown-linux-pauthtest</code> target
(<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1713">#1713</a>)</li>
<li>Fix nightly compilation error (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1783">#1783</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/rust-lang/cc-rs/blob/main/CHANGELOG.md">cc's
changelog</a>.</em></p>
<blockquote>
<h2><a
href="https://github.com/rust-lang/cc-rs/compare/cc-v1.2.66...cc-v1.2.67">1.2.67</a>
- 2026-07-11</h2>
<h3>Other</h3>
<ul>
<li>Fix clippy warning (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1788">#1788</a>)</li>
<li>Regenerate target info (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1785">#1785</a>)</li>
<li>Add support for <code>aarch64-unknown-linux-pauthtest</code> target
(<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1713">#1713</a>)</li>
<li>Fix nightly compilation error (<a
href="https://redirect.github.com/rust-lang/cc-rs/pull/1783">#1783</a>)</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/fa031a077aca2b19a31de895eafb17e965f35c89"><code>fa031a0</code></a>
chore(cc): release v1.2.67 (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1789">#1789</a>)</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/842aab16d28c77b30157f97bef777f8a643652b5"><code>842aab1</code></a>
Bump taiki-e/install-action from 2.81.8 to 2.82.8 (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1786">#1786</a>)</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/e2f07d0d68e3698d59d5e96d53c78f30e83ac845"><code>e2f07d0</code></a>
Fix clippy warning (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1788">#1788</a>)</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/8ced615d2c5349dfcb75ab064dfc600490264d89"><code>8ced615</code></a>
Regenerate target info (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1785">#1785</a>)</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/2943b5251297b6dabaf3f8e4c7d32560f69415f6"><code>2943b52</code></a>
Add missing todo for deprecated API</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/43ae1bf3ff399a7954c5b34cef7dc04d511f360e"><code>43ae1bf</code></a>
Add support for <code>aarch64-unknown-linux-pauthtest</code> target (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1713">#1713</a>)</li>
<li><a
href="https://github.com/rust-lang/cc-rs/commit/a5c584a1fa50ee93c7db9c3ff85b04a36df9100b"><code>a5c584a</code></a>
Fix nightly compilation error (<a
href="https://redirect.github.com/rust-lang/cc-rs/issues/1783">#1783</a>)</li>
<li>See full diff in <a
href="https://github.com/rust-lang/cc-rs/compare/cc-v1.2.66...cc-v1.2.67">compare
view</a></li>
</ul>
</details>
<br />

Updates `bytemuck` from 1.25.0 to 1.25.1
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/Lokathor/bytemuck/blob/main/changelog.md">bytemuck's
changelog</a>.</em></p>
<blockquote>
<h2>1.25.1</h2>
<ul>
<li><a
href="https://redirect.github.com/Lokathor/bytemuck/pull/348">Don't impl
core::error::Error on spirv</a>, which was causing a build error on that
target.</li>
<li>Added a reminder on <code>try_cast_slice</code> that empty slices
must still be aligned.</li>
</ul>
<h2>1.25</h2>
<ul>
<li><a
href="https://redirect.github.com/Lokathor/bytemuck/pull/333">Remove
extern &quot;stdcall&quot; fn ptr impls on non-x86-32 windows.</a></li>
<li><a href="https://redirect.github.com/Lokathor/bytemuck/pull/344">Fix
nightly_portable_simd after LaneCount removal.</a></li>
</ul>
<h2>1.24</h2>
<ul>
<li><a href="https://redirect.github.com/Lokathor/bytemuck/pull/322">use
new stable avx512 types from rust 1.89</a></li>
<li><a
href="https://redirect.github.com/Lokathor/bytemuck/pull/317">impl
AnyBitPattern for [MaybeUninit&lt;T: AnyBitPattern&gt;; N]</a></li>
<li>bump <code>derive</code> minimum version.</li>
</ul>
<h2>1.23.2</h2>
<ul>
<li>bump <code>derive</code> minimum version.</li>
</ul>
<h2>1.23.1</h2>
<ul>
<li>Added a windows-only <code>ZeroableInOption</code> impl for
&quot;stdcall&quot; functions.</li>
</ul>
<h2>1.23</h2>
<ul>
<li><code>impl_core_error</code> crate feature adds
<code>core::error::Error</code> impl.</li>
<li>More <code>ZeroableInOption</code> impls.</li>
</ul>
<h2>1.22</h2>
<ul>
<li>Add the <code>pod_saturating</code> feature, which adds
<code>Pod</code> impls for <code>Saturating&lt;T&gt;</code>
when <code>T</code> is already <code>Pod</code>.</li>
<li>A bump in the minimum <code>bytemuck_derive</code> dependency from
1.4.0 to 1.4.1 to
avoid a bug if you have a truly ancient <code>cargo.lock</code> file
sitting around.</li>
<li>Adds <code>Send</code> and <code>Sync</code> impls to
<code>BoxBytes</code>.</li>
</ul>
<h2>1.21</h2>
<ul>
<li>Implement <code>Pod</code> and <code>Zeroable</code> for
<code>core::arch::{x86, x86_64}::__m512</code>, <code>__m512d</code> and
<code>__m512i</code> without nightly.
Requires Rust 1.72, and is gated through the <code>avx512_simd</code>
cargo feature.</li>
<li>Allow the use of <code>must_cast_mut</code> and
<code>must_cast_slice_mut</code> in const contexts.
Requires Rust 1.83, and is gated through the
<code>must_cast_extra</code> cargo feature.</li>
<li>internal: introduced the <code>maybe_const_fn</code> macro that
allows defining some function
to be const depending upon some <code>cfg</code> predicate.</li>
</ul>
<h2>1.20</h2>
<ul>
<li>New functions to allocate zeroed <code>Arc</code> and
<code>Rc</code>. Requires Rust 1.82</li>
<li><code>TransparentWrapper</code> impls for
<code>core::cmp::Reverse</code> and
<code>core::num::Saturating</code>.</li>
</ul>
<!-- raw HTML omitted -->
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/cabc8e75899e67ad274959b6de27653558d01296"><code>cabc8e7</code></a>
chore: Release bytemuck version 1.25.1</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/2d4d8ca457a552bd9310a5a10327151a705b9f0b"><code>2d4d8ca</code></a>
changelog</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/946e7a905f7651b1dfb568d5045b8bcff1b56f26"><code>946e7a9</code></a>
chore: Release bytemuck_derive version 1.11.0</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/8a8f7cf4c9988a668336a792c78bbbb0a52ed8ef"><code>8a8f7cf</code></a>
changelog derive</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/ee6742e68cdb2a7058196a1cf13834ffbdac40d3"><code>ee6742e</code></a>
changelog</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/e2d1c7f2e9797d4b2f3de5a16b6a70879e53a8d8"><code>e2d1c7f</code></a>
Don't impl core::error::Error on spirv (<a
href="https://redirect.github.com/Lokathor/bytemuck/issues/348">#348</a>)</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/7dd71742f67630949e5e9a21bb74469a69c1bce2"><code>7dd7174</code></a>
make the note more terse</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/24b1b71c599eb1e2b70b6059b851d4c264991e71"><code>24b1b71</code></a>
Update Rust version in CI workflow to 1.71.0</li>
<li><a
href="https://github.com/Lokathor/bytemuck/commit/f0dfc1bc6ef0de704ffd0b64231f9c3565d65ac6"><code>f0dfc1b</code></a>
docs: note that an empty slice must still satisfy target alignment in
cast_sl...</li>
<li>See full diff in <a
href="https://github.com/Lokathor/bytemuck/compare/v1.25.0...v1.25.1">compare
view</a></li>
</ul>
</details>
<br />

Updates `clap` from 4.6.1 to 4.6.2
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/clap-rs/clap/releases">clap's
releases</a>.</em></p>
<blockquote>
<h2>v4.6.2</h2>
<h2>[4.6.2] - 2026-07-15</h2>
<h3>Fixes</h3>
<ul>
<li><em>(help)</em> Say <code>alias</code> when there is only one</li>
</ul>
</blockquote>
</details>
<details>
<summary>Changelog</summary>
<p><em>Sourced from <a
href="https://github.com/clap-rs/clap/blob/master/CHANGELOG.md">clap's
changelog</a>.</em></p>
<blockquote>
<h2>[4.6.2] - 2026-07-15</h2>
<h3>Fixes</h3>
<ul>
<li><em>(help)</em> Say <code>alias</code> when there is only one</li>
</ul>
</blockquote>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/clap-rs/clap/commit/0fe0be302726f4253b9bee27eed48438c92917aa"><code>0fe0be3</code></a>
chore: Release</li>
<li><a
href="https://github.com/clap-rs/clap/commit/480af9d045453f4ab96d9bdd4d4b9f5aab3c272f"><code>480af9d</code></a>
docs: Update changelog</li>
<li><a
href="https://github.com/clap-rs/clap/commit/2b3ddd0294a147d1eda917cb303243bcde0c12ee"><code>2b3ddd0</code></a>
Merge pull request <a
href="https://redirect.github.com/clap-rs/clap/issues/6340">#6340</a>
from liskin/fix-completion-escape</li>
<li><a
href="https://github.com/clap-rs/clap/commit/7ffe7399ff032cc247eb0449cf8fcdfbfe55a4ec"><code>7ffe739</code></a>
fix(complete): Do not suggest options after &quot;--&quot;</li>
<li><a
href="https://github.com/clap-rs/clap/commit/d47fc4f8a5e9fcc16d0cae15b51e6eb1a8ed5832"><code>d47fc4f</code></a>
test(complete): Options suggested after escape (<code>--</code>)</li>
<li>See full diff in <a
href="https://github.com/clap-rs/clap/compare/clap_complete-v4.6.1...clap_complete-v4.6.2">compare
view</a></li>
</ul>
</details>
<br />


Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore <dependency name> major version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's major version (unless you unignore this specific
dependency's major version or upgrade to it yourself)
- `@dependabot ignore <dependency name> minor version` will close this
group update PR and stop Dependabot creating any more for the specific
dependency's minor version (unless you unignore this specific
dependency's minor version or upgrade to it yourself)
- `@dependabot ignore <dependency name>` will close this group update PR
and stop Dependabot creating any more for the specific dependency
(unless you unignore this specific dependency or upgrade to it yourself)
- `@dependabot unignore <dependency name>` will remove all of the ignore
conditions of the specified dependency
- `@dependabot unignore <dependency name> <ignore condition>` will
remove the ignore condition of the specified dependency and ignore
conditions


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Nicola Assolini <nicola.assolini@quantinuum.com>